# Generated by Django 6.0.5 on 2026-05-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='avg_completion_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='workflow',
            name='bottleneck_step_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='optimization_suggestions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='is_timeout_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='predicted_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='step_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='timeout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('timeout', 'Timeout'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
